# .travis.yml
language: 
  python
python:
  "3.7.4"
script: 
  - make travis_test
  - coverage run --source=. -m pytest
install:
  - pip install coveralls
after_success:
  - coveralls
branches:
  only:
    - master