# .travis.yml
language: 
  python
python:
  "3.7.4"
script: 
  - make travis_test
  - coverage run -m pytest src/tests
install:
  - pip install coveralls pytest
after_success:
  - coveralls
branches:
  only:
    - master